### ISSUE TITLE
How to use amunmt_server.py?

### ISSUE THREAD

**Issue by mehmedes** [amunmt/amunmt#31]
Hi all,

After running the amunmt_server.py, how do I send translation requests and get back translations?
This is what it looks like when I run the .py with my configs.

```
sariyildiznureddin@instance-2:~/amunmt/scripts$ python amunmt_server.py -c config.ens.yml                       
[Thu Jan 26 09:21:00 2017] (I) Options: 
allow-unk: false
batch-size: 1
beam-size: 12
bpe:
  - /home/sariyildiznureddin/de-en/deen.bpe
bunch-size: 1
cpu-threads: 8
devices: [0]
gpu-threads: 0
maxi-batch: 1
mini-batch: 1
n-best: false
no-debpe: false
normalize: false
relative-paths: true
return-alignment: false
scorers:
  F0:
    path: /home/sariyildiznureddin/de-en/model-ens1.npz
    type: Nematus
  F1:
    path: /home/sariyildiznureddin/de-en/model-ens2.npz
    type: Nematus
  F2:
    path: /home/sariyildiznureddin/de-en/model-ens3.npz
    type: Nematus
  F3:
    path: /home/sariyildiznureddin/de-en/model-ens4.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - /home/sariyildiznureddin/de-en/vocab.de.json
target-vocab: /home/sariyildiznureddin/de-en/vocab.en.json
weights:
  F0: 1
  F1: 1
  F2: 1
  F3: 1
wipo: false
[Thu Jan 26 09:21:02 2017] (I) Loading scorers...
[Thu Jan 26 09:21:02 2017] (I) Loading model /home/sariyildiznureddin/de-en/model-ens1.npz
[Thu Jan 26 09:21:02 2017] (I) Loading model /home/sariyildiznureddin/de-en/model-ens2.npz
[Thu Jan 26 09:21:03 2017] (I) Loading model /home/sariyildiznureddin/de-en/model-ens3.npz
[Thu Jan 26 09:21:03 2017] (I) Loading model /home/sariyildiznureddin/de-en/model-ens4.npz
[Thu Jan 26 09:21:04 2017] (I) Reading from stdin
[Thu Jan 26 09:21:04 2017] (I) using bpe: /home/sariyildiznureddin/de-en/deen.bpe
[Thu Jan 26 09:21:04 2017] (I) De-BPE output
```

Please let me know if these kind of questions are out of the scope of this forum. I know it's actually not a  system issue but the lack of my knowledge.
