### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by mehmedes** [amunmt/amunmt#37]
Why is the output of nematus and amunmt different even though I use the same model?

Nematus translates 
> A win like this might be close.
into
> Ein Sieg wie dieser könnte nahe sein  - which is a correct translation.

Amunmt translates the same sentence into
> Ein Sieg wie dieser könnte schließen. - schließen would rather make sense in the context of closing a door.

This is my Nematus config:
```
THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=$device,on_unused_input=warn python $nematus/nematus/translate.py \
     -m model-ens4.npz \
     -k 50 -n -p 1 --suppress-unk
```

And this is my Amunmt config:
```
allow-unk: false
batch-size: 1
beam-size: 50
bpe:
  - /home/sariyildiznureddin/en-de/ende.bpe
bunch-size: 1
cpu-threads: 4
devices: [0]
gpu-threads: 0
n-best: false
no-debpe: false
normalize: false
relative-paths: true
return-alignment: false
scorers:
  F0:
    path: /home/sariyildiznureddin/en-de/model-ens4.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - /home/sariyildiznureddin/en-de/vocab.en.json
target-vocab: /home/sariyildiznureddin/en-de/vocab.de.json
weights:
  F0: 1
wipo: false
```
