### ISSUE TITLE
what():  load_the_npy_file: failed fread

### ISSUE THREAD

**Issue by mehmedes** [amunmt/amunmt#41]
Dear AmuNMT team,

I've tried to adapt a model by continuing training on an in-domain set. When I try to use that model for translation in AmuNMT, I get the following error (Decoding with Nematus works wel):
```
[Fri Feb 17 18:38:01 2017] (I) Loading scorers...
[Fri Feb 17 18:38:01 2017] (I) Loading model /home/sariymx/en-de/klin.npz
terminate called after throwing an instance of 'std::runtime_error'
  what():  load_the_npy_file: failed fread
```

This is what the adapted model json looks like:
```
{
  "prior_model": null, 
  "map_decay_c": 0.0, 
  "mrt_samples": 100, 
  "dropout_hidden": 0.2, 
  "decoder": "gru_cond", 
  "sort_by_length": true, 
  "decay_c": 0.0, 
  "dropout_source": 0.1, 
  "model_version": 0.1, 
  "tie_decoder_embeddings": false, 
  "domain_interpolation_indomain_datasets": [
    "indomain.en", 
    "indomain.fr"
  ], 
  "max_epochs": 1, 
  "dispFreq": 1000, 
  "finetune_only_last": false, 
  "domain_interpolation_min": 0.1, 
  "overwrite": false, 
  "validFreq": 10000, 
  "mrt_samples_meanloss": 10, 
  "dropout_embedding": 0.2, 
  "external_validation_script": null, 
  "mrt_ml_mix": 0, 
  "clip_c": 1.0, 
  "n_words_src": 85000, 
  "saveto": "model-ens4.npz", 
  "dropout_target": 0.1, 
  "objective": "CE", 
  "valid_batch_size": 80, 
  "n_words": 85000, 
  "mrt_alpha": 0.005, 
  "tie_encoder_decoder_embeddings": false, 
  "optimizer": "adadelta", 
  "alpha_c": 0.0, 
  "mrt_loss": "SENTENCEBLEU n=4", 
  "batch_size": 80, 
  "use_domain_interpolation": false, 
  "lrate": 0.0001, 
  "valid_datasets": null, 
  "pos_win": 10, 
  "encoder": "gru", 
  "shuffle_each_epoch": true, 
  "mrt_reference": false, 
  "dim": 1024, 
  "use_dropout": false, 
  "datasets": [
    "data/corpus.bpe.en", 
    "data/corpus.bpe.de"
  ], 
  "dim_word": 500, 
  "sampleFreq": 10000, 
  "patience": 10, 
  "maxibatch_size": 20, 
  "finetune": false, 
  "factors": 1, 
  "dictionaries": [
    "vocab.en.json", 
    "vocab.de.json"
  ], 
  "reload_": true, 
  "maxlen": 50, 
  "finish_after": 10000000, 
  "domain_interpolation_inc": 0.1, 
  "dim_per_factor": [
    500
  ], 
  "saveFreq": 30000
}
```

My configs are:
```
allow-unk: false
batch-size: 1
beam-size: 12
bpe:
  - /home/sariymx/en-de/ende.bpe
bunch-size: 1
cpu-threads: 16
devices: [0]
gpu-threads: 0
n-best: false
no-debpe: false
normalize: true
relative-paths: true
return-alignment: false
scorers:
  F0:
    path: /home/sariymx/en-de/klin.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - /home/sariymx/en-de/vocab.en.json
target-vocab: /home/sariymx/en-de/vocab.de.json
weights:
  F0: 1
wipo: false
```

The command I used in Nematus, which worked, were:
```
THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=$device,on_unused_input=warn python $nematus/nematus/translate.py \
    -m klin.npz \
     -k 12 -n -p 1 --suppress-un
```

Thanks for taking your time and your great work!
